services:
  - type: web
    name: relex
    runtime: python
    plan: free
    branch: deploy
    buildCommand: pip install -r requirements.txt
    startCommand: python pipeline/serve.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TOKENIZERS_PARALLELISM
        value: "false"
